bboard/urls.py
from django.urls import path

from bboard.views import index, by_rubric, BbCreateView

app_name = 'bboard'

urlpatterns = [
    path('add/', BbCreateView.as_view(), name='add'),
    path('<int:rubric_id>/', by_rubric, name='by_rubric'),
    path('', index, name='index'),
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls', namespace='bboard')),
]

bboard/models.py
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models


def is_active_default():
    return True


def validate_even(val):
    if val % 2 != 0:
        raise ValidationError('Число %(value)s нечётное', code='odd',
                              params={'value': val})


class MinMaxValueValidator:
    def __init__(self, min_value, max_value):
        self.min_value = min_value
        self.max_value = max_value

    def __call__(self, val):
        if val < self.min_value or val > self.max_value:
            raise ValidationError('Введённое число должно находиться в диапазоне от '
                                  '%(min)s до %(max)s',
                                  code='out_of_range',
                                  params={'min': self.min_value, 'max': self.max_value})


class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, unique=True,
                            verbose_name='Название')

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
    #     if self.is_model_correct():
    #         super().save(*args, **kwargs)

    # def delete(self, *args, **kwargs):
    #     super().delete(*args, **kwargs)

    def get_absolute_url(self):
        return f"/{self.pk}/"

    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'
        ordering = ['name']


class Bb(models.Model):
    # KINDS = (
    #     ('b', 'Куплю'),
    #     ('s', 'Продам'),
    #     ('c', 'Обменяю'),
    # )
    # KINDS = (
    #     ('Купля-продажа', (
    #         ('b', 'Куплю'),
    #         ('s', 'Продам'),
    #     )),
    #     ('Обмен', (
    #         ('c', 'Обменяю'),
    #     ))
    # )
    KINDS = (
        (None, 'Выберите тип публикуемого объявления'),
        ('b', 'Куплю'),
        ('s', 'Продам'),
        ('c', 'Обменяю'),
    )

    kind = models.CharField(max_length=1, choices=KINDS, default='s')

    rubric = models.ForeignKey('Rubric', null=True, on_delete=models.PROTECT,
                               verbose_name='Рубрика', related_name='entries')
    title = models.CharField(max_length=50, verbose_name='Товар',
                             validators=[
                                 validators.RegexValidator(
                                     regex='^.{4,}$',
                                     message='Слишком мало букавак!',
                                     code='invalid',
                                 )
                             ],
                             error_messages={'invalid': 'Неправильное название товара!'}
                             )  # primary_key=True
    content = models.TextField(null=True, blank=True, verbose_name='Описание')
    # price = models.FloatField(  # default=0,
    #                           null=True, blank=True, verbose_name='Цена')
    price = models.DecimalField(max_digits=15, decimal_places=2,
                                null=True, blank=True, verbose_name='Цена',
                                validators=[validate_even,
                                            # MinMaxValueValidator(100, 1_000_000)
                                            ])
    published = models.DateTimeField(auto_now_add=True, db_index=True,
                                     verbose_name='Опубликовано')
    # is_active = models.BooleanField(  # default=True
    #                                 default=is_active_default
    #                                 )

    def title_and_price(self):
        if self.price:
            return f'{self.title} ({self.price:.2f})'
        else:
            return self.title

    title_and_price.short_description = 'Название и цена'

    def __str__(self):
        return f'{self.title} ({self.price} тг.)'

    def clean(self):
        errors = {}
        if not self.content:
            errors['content'] = ValidationError('Укажите описание продаваемого товара')

        if self.price and self.price < 0:
            errors['price'] = ValidationError('Укажите неотрицательное значение цены')

        if errors:
            raise ValidationError(errors)

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['-published', 'title']
        get_latest_by = 'published'

newapp/models.py
from django.db import models


class MyNewModel(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    KINDS = (
        (None, 'Выберите тип'),
        ('b', 'er'),
        ('s', 'ter'),
        ('c', 'ber'),
    )
    tip = models.CharField(max_length=1, choices=KINDS, default='s')

testapp/models.py
from django.contrib.auth.models import User
from django.db import models


class AdvUser(models.Model):
    is_activated = models.BooleanField(default=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Spare(models.Model):
    name = models.CharField(max_length=30)


class Machine(models.Model):
    name = models.CharField(max_length=30)
    spares = models.ManyToManyField(Spare)

bboard/forms.py
from django.forms import ModelForm

from bboard.models import Bb


class BbForm(ModelForm):
    class Meta:
        model = Bb
        fields = ('title', 'content', 'price', 'rubric')

bboard/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from bboard.forms import BbForm
from bboard.models import Bb, Rubric


# def index(request):
#     template = loader.get_template('bboard/index.html')
#     bbs = Bb.objects.order_by('-published')
#     context = {'bbs': bbs}
#
#     return HttpResponse(template.render(context, request))


def index(request):
    bbs = Bb.objects.order_by('-published')
    rubrics = Rubric.objects.all()
    context = {'bbs': bbs, 'rubrics': rubrics}

    return render(request, 'bboard/index.html', context)


def by_rubric(request, rubric_id):
    # bbs = Bb.objects.filter(rubric=rubric_id)
    rubrics = Rubric.objects.all()
    current_rubric = Rubric.objects.get(pk=rubric_id)

    bbs = current_rubric.entries.all()

    context = {'bbs': bbs, 'rubrics': rubrics, 'current_rubric': current_rubric}

    return render(request, 'bboard/by_rubric.html', context)


class BbCreateView(CreateView):
    template_name = 'bboard/create.html'
    form_class = BbForm
    success_url = reverse_lazy('bboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()
        return context

newapp/views.py
from django.shortcuts import render

# Create your views here.

testapp/views.py
from django.shortcuts import render

# Create your views here.

bboard/templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}


{% block title %}{{ current_rubric }}{% endblock %}

{% block content %}
    {% for bb in bbs %}
    <div>
        <h2>{{ bb.title }}</h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}

bboard/templates/bboard/create.html
{% extends "layout/basic.html" %}



{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
{% endblock %}

bboard/templates/bboard/index.html
{% extends "layout/basic.html" %}

{% block content %}
    {% for bb in bbs %}
    <div>
{#        <h2>{{ bb.title }}</h2> #}
        <h2>{{ bb.title_and_price }}</h2>
        <p>{{ bb.content }}</p>
        {# <p><a href="/{{ bb.rubric.pk }}/">{{ bb.rubric.name }}</a></p> #}
        <p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">{{ bb.rubric.name }}</a></p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}
{% endblock %}

bboard/templates/layout/basic.html
<!DOCTYPE html>

{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Главная{% endblock %} :: Доска объявлений</title>

    <link rel="stylesheet" href="{% static 'bboard/style.css' %}">
</head>
<body>

<header>
    <h1>Объявления</h1>
</header>

<nav>
    <a href="{% url 'bboard:index' %}">Главная</a>
    <a href="{% url 'bboard:add' %}">Добавить</a>
    {% for rubric in rubrics %}
        {# <a href="/{{ rubric.pk }}/">{{ rubric.name }}</a> #}
{#        <a href="{% url 'bboard:by_rubric' rubric.pk %}">{{ rubric.name }}</a> #}
        <a href="{{ rubric.get_absolute_url }}">{{ rubric.name }}</a>
    {% endfor %}
</nav>

<section>
    {% block content %}
    {% endblock %}
</section>

</body>
</html>